export enum Category {
	CHINESE_JUNK = 'CHINESE JUNK',
	GETAWAY_PLANS = 'GETAWAY PLANS',
	UNNECESSARY_SUPPLEMENTS = 'UNNECESSARY SUPPLEMENTS',
	ONE_MONTH_MAKE_ME_HAPPY_ITEMS = 'ONE MONTH MAKE ME HAPPY ITEMS',
	TOO_EXPENSIVE_FOOD_RELATED_THINGS = 'TOO EXPENSIVE FOOD RELATED THINGS'
}
